server:
  port: 8761


# Eureka 서버 이름
spring:
  application:
    name: discoverservice

# Eureka Server 설정
eureka:
  server:
    enable-self-preservation: true
    expected-client-renewal-interval-seconds: 100
    eviction-interval-timer-in-ms: 600
    renewal-percent-threshold: 0.85
  client:
    register-with-eureka: false
    fetch-registry: false

# End Point 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"